// Code generated by jrpc. DO NOT EDIT.

// Package {{.PkgName}} is an auto-generated package providing HTTP handler
// functions that wrap handlers in the {{.SpecPkgPath}} package.
package {{.PkgName}}

import (
	"encoding/json"
	"context"
	"fmt"
	"net/http"
	"{{.SpecPkgPath}}"
	{{range $pkg, $element := .Imports -}}
	"{{$pkg}}"
	{{end -}}
)

type JSONCaller func(ctx context.Context, req json.RawMessage) (json.RawMessage, error)

func (j JSONCaller) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	d := json.NewDecoder(r.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		http.Error(w, "the json request could not be decoded", http.StatusBadRequest)
		return
	}

	resp, err := j(r.Context(), rawReqBody)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Write(resp)
}

func HTTPHandler(recv *{{$.SpecPkgName}}.{{.Receiver}}) http.Handler {
	mux := http.NewServeMux()
  {{- range $method := .Methods}}
	mux.Handle("/{{$method.Name}}", {{$.Receiver}}{{$method.Name}}Caller(recv))
  {{- end}}
	return mux
}

type RPCCaller func(method string) (JSONCaller, error)

func Caller(recv *{{$.SpecPkgName}}.{{.Receiver}}) RPCCaller {
	methods := map[string]JSONCaller{
		{{range $method := .Methods -}}
		"{{$method.Name}}": {{$.Receiver}}{{$method.Name}}Caller(recv),
		{{end}}
	}
	return func(method string) (JSONCaller, error) {
		caller, ok := methods[method]
		if !ok {
			return nil, fmt.Errorf("unknown method %s", method)
		}
		return caller, nil
	}
}

{{range $method := .Methods}}
func {{$.Receiver}}{{$method.Name}}Caller(recv *{{$.SpecPkgName}}.{{$.Receiver}}) JSONCaller {
	return func (ctx context.Context, req json.RawMessage) (json.RawMessage, error) {
		var input {{$method.Takes.Type}}
		err := json.Unmarshal(req, &input)
		if err != nil {
			return nil, err
		}

		resp, err := recv.{{$method.Name}}(ctx, input)
		if err != nil {
			return nil, err
		}

		respBytes, err := json.Marshal(resp)
		if err != nil {
			return nil, err
		}
		return respBytes, nil
	}
}
{{end}}
